export * from '@/lib/email/constants'
export * from '@/lib/email/can-send'
export * from '@/lib/email/consent'
export * from '@/lib/email/preferences-db'
export * from '@/lib/email/sender'
export * from '@/lib/email/tokens'
export { renderDailyBriefEmail } from '@/lib/email/templates/daily-brief'
export { renderWeeklyDigestEmail } from '@/lib/email/templates/weekly-digest'
export { renderProductUpdateEmail } from '@/lib/email/templates/product-update'
export { renderConnectorOfflineAlertEmail } from '@/lib/email/templates/connector-offline'
export { renderSyncFailureAlertEmail } from '@/lib/email/templates/sync-failure'
export { renderFounderNoteEmail } from '@/lib/email/templates/founder-note'
export { renderEducationalContentEmail } from '@/lib/email/templates/educational-content'
export { renderPartnerOfferEmail } from '@/lib/email/templates/partner-offer'
export * from '@/lib/email/agents'
