export * from '@/lib/email/agents/types'
export * from '@/lib/email/agents/config'
export { routeEmailIntake, classifyIntake } from '@/lib/email/agents/intake-router'
export { validateEmailCompliance } from '@/lib/email/agents/compliance'
export { checkPreferenceGate } from '@/lib/email/agents/preference-gate'
export { selectAudienceRecipients } from '@/lib/email/agents/audience-segment'
export { scheduleEmailSend } from '@/lib/email/agents/scheduler'
export { generateEmailDraft } from '@/lib/email/agents/generate-draft'
export { runEmailIntakePipeline, dispatchDueQueuedEmails } from '@/lib/email/agents/pipeline'
export * from '@/lib/email/agents/queue-db'
export * from '@/lib/email/agents/delivery-log-db'
export { buildDailyBriefIntakeFromLatest, parseDossierToIntakePayload, resolveLatestDossierPath, resolveDailyBriefIntake } from '@/lib/email/agents/dossier-intake'
export { buildWeeklyDigestIntakeFromManifest } from '@/lib/email/agents/weekly-digest-intake'
export { publishDailyBriefSnapshot, fetchDailyBriefSnapshot } from '@/lib/email/agents/intake-snapshot'
export { loadAccessEnv, jdaiContentEngineRoot } from '@/lib/email/agents/load-env'
